#!/bin/bash

# source this file at the bottom of ~/.bashrc

# exports
# development environment
export ENV="development"

# golang
export GOROOT=/usr/local/go # we install here manually in ubuntu.sh
export GOPATH=$HOME/code
export GO111MODULE=on
export PATH=$PATH:$GOROOT/bin
export PATH=$PATH:$GOPATH/bin



# aliases
alias upgrade="sudo apt-get update -y && sudo apt-get upgrade -y"
alias size="ls -l --block-size=M"
alias desk="cd ~/Desktop"
alias nvimcfg="nvim ~/.config/nvim/init.vim"
alias emacs="emacs -nw"
alias sudo="sudo "
alias screenrc="nvim ~/.screenrc"
alias open="nautilus -s ."
# enables e.g. echo test | xclip
alias xclip="xclip -selection c"
alias home="cd ~"
alias weather='curl wttr.in'
alias scm="rlwrap mit-scheme" # makes arrow keys work in scheme
alias rkt="rlwrap racket" # makes arrow keys work in racket 

# set nvim as default editor
export VISUAL=nvim
export EDITOR="$VISUAL"

# functions
function commit {
  #msg=$1
  git add -A .
  git commit -m "$1"
}


function bp {
  nvim ~/.misrabrc
}
function bpp {
  source ~/.misrabrc
}
function gogit {
  cd ~/code/src/github.com/
}
function cb {
  cargo bench
}
function ct {
  cargo test -- --nocapture
}
function cr {
  cargo run -- $@
}
function jp {
  jupyter notebook
}
# usage: push [branch] "[commit message]"
function push {
  commit="commit"
  if [[ ! -z $2 ]]; then
    commit="$2"
  fi
  
  git add -A . && git commit -m $commit
  
  if [[ ! -z $1 ]]; then
    git push origin $1
  else
    git push origin main
  fi
}
# usage: pull [branch]
function pull {
  if [[ ! -z $1 ]]; then
    git pull origin $1
  else
    git pull origin main
  fi
}
function pullf {
  git fetch --all
  git reset --hard origin/main
}

# colors
parse_git_branch() {
     git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ (\1)/'
}
# template
#export PS1="\u@\h \[\033[32m\]\w\[\033[33m\]\$(parse_git_branch)\[\033[00m\] $ "
# my version
export PS1="\[\033[1;37m\][\u]\[\e[0m\] \[\033[32m\]\w\[\033[33m\]\$(parse_git_branch)\[\033[00m\] >> "

export PATH=$PATH:/usr/local/go/bin


#  android studio
# export ANDROID_HOME=$HOME/Android/Sdk
# export PATH=$PATH:$ANDROID_HOME/tools

export PATH="$HOME/.local/bin:$PATH"
